# Generated by Django 5.2.17 on 2026-08-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'На складе'), ('READY', 'Готово к продаже'), ('IN_SERVICE', 'В сервисе'), ('SOLD', 'Продано')], default='IN_STOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
