# Generated by Django 5.2.17 on 2026-08-28 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_batch_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество в резерве')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания резерва')),
                ('is_fulfilled', models.BooleanField(default=False, verbose_name='Исполнен')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.client', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Резерв',
                'verbose_name_plural': 'Резервы',
            },
        ),
    ]
