# Generated by Django 5.2.17 on 2026-09-02 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='defect_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.defecttype', verbose_name='Тип неисправности'),
        ),
        migrations.AddField(
            model_name='unit',
            name='service_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='unit',
            name='service_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата приёма в сервис'),
        ),
        migrations.AddField(
            model_name='unit',
            name='task_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на задачу'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
