# Generated by Django 5.2.17 on 2026-09-03 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_unit_defect_type_unit_service_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Приёмка (партия)', 'verbose_name_plural': 'Приёмки (партии)'},
        ),
        migrations.AlterModelOptions(
            name='defecttype',
            options={'verbose_name': 'Вид неисправности', 'verbose_name_plural': 'Виды неисправностей'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'verbose_name': 'Тип устройства', 'verbose_name_plural': 'Тип устройств'},
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отгрузки резерва')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.client', verbose_name='Наименование клиента')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.reservation', verbose_name='Резерв')),
            ],
            options={
                'verbose_name': 'Отгрузка',
                'verbose_name_plural': 'Отгрузки',
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.shipment')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unit', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
    ]
