# Generated by Django 5.2.17 on 2026-09-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_batch_options_alter_defecttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='service_resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата из сервиса'),
        ),
    ]
