# Generated by Django 5.2.17 on 2026-09-10 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_unit_service_resolved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество в резерве')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Товар')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.reservation', verbose_name='Резервы')),
            ],
            options={
                'verbose_name': 'Позиция резерва',
                'verbose_name_plural': 'Позиции резервов',
            },
        ),
    ]
