# Generated by Django 5.2.17 on 2026-09-29 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_reservation_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.reservation', verbose_name='Резерв'),
        ),
    ]
