# Generated by Django 5.2.17 on 2026-09-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_unit_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_of_shipment',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отгрузки'),
        ),
    ]
