# Generated by Django 5.2.17 on 2026-10-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_reservation_date_of_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='staus',
            field=models.BooleanField(default=False, verbose_name='Отменён'),
        ),
    ]
