# Generated by Django 5.2.17 on 2026-10-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_reservationitem_staus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationitem',
            name='staus',
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Отменён'),
        ),
    ]
